services:
  frontend:
    restart: always
    image: portal
    ports:
      - "5000:80"
  auth:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
  chatservice:
    restart: always
    image: net
    ports:
      - "5288:5288"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Q(&WF*YWQFF(3408"
      ACCEPT_EULA: "Y"
networks:
  default:
    name: chatapp
    driver: bridge
